"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { GoogleAuthProvider, createUserWithEmailAndPassword, sendPasswordResetEmail, signInWithEmailAndPassword, signInWithPopup, signOut } from "firebase/auth";
import { doc, getDoc, setDoc } from "firebase/firestore";
import { auth, db } from "@/lib/firebase/client";

type Role = "proprietaire" | "locataire";
type Country = { flag: string; name: string; code: string };
const countries: Country[] = [
  { flag: "🇧🇯", name: "Bénin", code: "+229" }, { flag: "🇧🇫", name: "Burkina Faso", code: "+226" }, { flag: "🇨🇲", name: "Cameroun", code: "+237" }, { flag: "🇰🇲", name: "Comores", code: "+269" }, { flag: "🇨🇬", name: "Congo-Brazzaville", code: "+242" }, { flag: "🇨🇮", name: "Côte d’Ivoire", code: "+225" }, { flag: "🇩🇯", name: "Djibouti", code: "+253" }, { flag: "🇬🇦", name: "Gabon", code: "+241" }, { flag: "🇬🇳", name: "Guinée", code: "+224" }, { flag: "🇬🇶", name: "Guinée équatoriale", code: "+240" }, { flag: "🇲🇬", name: "Madagascar", code: "+261" }, { flag: "🇲🇱", name: "Mali", code: "+223" }, { flag: "🇲🇷", name: "Mauritanie", code: "+222" }, { flag: "🇳🇪", name: "Niger", code: "+227" }, { flag: "🇨🇫", name: "République centrafricaine", code: "+236" }, { flag: "🇨🇩", name: "RD Congo", code: "+243" }, { flag: "🇷🇼", name: "Rwanda", code: "+250" }, { flag: "🇸🇳", name: "Sénégal", code: "+221" }, { flag: "🇹🇩", name: "Tchad", code: "+235" }, { flag: "🇹🇬", name: "Togo", code: "+228" },
];

function accountEmail(phone: string) { return `${phone.replace(/\D/g, "")}@accounts.bailio.local`; }
function makeCode() { return String(Math.floor(100000 + Math.random() * 900000)); }

export function AuthCard({ expectedRole, initialMode = "login" }: { expectedRole: Role; initialMode?: "login" | "register" }) {
  const router = useRouter();
  const [mode, setMode] = useState(initialMode); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [googleUser, setGoogleUser] = useState<{ uid: string; email: string | null } | null>(null);

  async function createVerification(uid: string) { const code = makeCode(); await setDoc(doc(db, "codesVerification", uid), { uid, code, statut: "en_attente", createdAt: Date.now(), expiresAt: Date.now() + 600000 }); return code; }
  async function finish(uid: string, role: Role, status: string) { document.cookie = `bailio-role=${role}; path=/; max-age=2592000; samesite=lax`; document.cookie = `bailio-status=${status}; path=/; max-age=2592000; samesite=lax`; if (status !== "actif") router.push(`/verification?uid=${uid}`); else router.push(role === "locataire" ? "/locataire/dashboard" : "/dashboard"); }

  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setLoading(true); setError(""); setNotice(""); const form = new FormData(event.currentTarget); const country = countries.find((item) => item.code === form.get("country")) ?? countries[0]; const phone = `${country.code}${String(form.get("phone") ?? "")}`; const email = accountEmail(phone);
    try {
      if (mode === "register") {
        const credential = await createUserWithEmailAndPassword(auth, email, String(form.get("password") ?? ""));
        await setDoc(doc(db, "users", credential.user.uid), { uid: credential.user.uid, nom: form.get("name"), telephone: phone, email, role: expectedRole, statut: "en_attente", createdAt: new Date().toISOString() });
        const code = await createVerification(credential.user.uid); setNotice(`Code de vérification envoyé. Code de test local : ${code}`); router.push(`/verification?uid=${credential.user.uid}`);
      } else {
        const credential = await signInWithEmailAndPassword(auth, email, String(form.get("password") ?? "")); const profile = await getDoc(doc(db, "users", credential.user.uid)); const data = profile.data();
        if (data?.role !== expectedRole) { await signOut(auth); throw new Error(expectedRole === "locataire" ? "WRONG_OWNER_SPACE" : "WRONG_TENANT_SPACE"); }
        await finish(credential.user.uid, expectedRole, data?.statut ?? "en_attente");
      }
    } catch (exception) { const code = exception instanceof Error ? exception.message : ""; const messages: Record<string, string> = { WRONG_OWNER_SPACE: "Ce compte est un compte locataire. Utilisez l’espace locataire.", WRONG_TENANT_SPACE: "Ce compte est un compte propriétaire. Utilisez l’espace propriétaire.", "auth/email-already-in-use": "Un compte existe déjà avec ce numéro.", "auth/invalid-credential": "Numéro de téléphone ou mot de passe incorrect." }; setError(messages[code] ?? "Impossible de finaliser cette opération. Vérifiez vos informations."); } finally { setLoading(false); }
  }

  async function googleSignIn() { setLoading(true); setError(""); try { const result = await signInWithPopup(auth, new GoogleAuthProvider()); const profile = await getDoc(doc(db, "users", result.user.uid)); const data = profile.data(); if (data?.role && data.role !== expectedRole) throw new Error(expectedRole === "locataire" ? "WRONG_OWNER_SPACE" : "WRONG_TENANT_SPACE"); if (!data?.telephone || !data?.role) { setGoogleUser({ uid: result.user.uid, email: result.user.email }); return; } await finish(result.user.uid, expectedRole, data.statut ?? "en_attente"); } catch (exception) { const code = exception instanceof Error ? exception.message : ""; setError(code === "WRONG_OWNER_SPACE" ? "Ce compte est un compte locataire. Utilisez l’espace locataire." : code === "WRONG_TENANT_SPACE" ? "Ce compte est un compte propriétaire. Utilisez l’espace propriétaire." : "Connexion Google impossible."); } finally { setLoading(false); } }
  async function completeGoogle(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); try { const form = new FormData(event.currentTarget); const country = countries.find((item) => item.code === form.get("country")) ?? countries[0]; const phone = `${country.code}${String(form.get("phone") ?? "")}`; await setDoc(doc(db, "users", googleUser!.uid), { uid: googleUser!.uid, email: googleUser!.email, telephone: phone, nom: form.get("name"), role: expectedRole, statut: "en_attente", createdAt: new Date().toISOString() }); const code = await createVerification(googleUser!.uid); setNotice(`Code de test local : ${code}`); router.push(`/verification?uid=${googleUser!.uid}`); } catch { setError("Impossible de compléter votre profil Google."); } finally { setLoading(false); } }
  async function resetPassword() { const phone = window.prompt("Entrez votre numéro de téléphone"); if (!phone) return; try { await sendPasswordResetEmail(auth, accountEmail(phone)); setNotice("Un lien de réinitialisation a été envoyé si le compte existe."); } catch { setError("Impossible d’envoyer le lien de réinitialisation."); } }

  const title = expectedRole === "locataire" ? "Espace locataire" : "Espace propriétaire";
  return <main className="auth-page"><Link className="brand auth-brand" href="/"><span className="brand-mark">B</span><span>Bail<span className="brand-accent">io</span></span></Link><section className="auth-card"><div className="auth-card-heading"><span className="auth-symbol">{expectedRole === "locataire" ? "♙" : "⌂"}</span><p className="eyebrow">{title.toUpperCase()}</p><h1>{googleUser ? "Complétez votre profil" : mode === "register" ? "Créer votre compte" : "Se connecter"}</h1><p>{googleUser ? "Votre numéro et votre nom sont nécessaires." : "Un accès simple et sécurisé à votre espace."}</p></div>{googleUser ? <form className="form-stack" onSubmit={completeGoogle}><label>Nom complet<input name="name" required placeholder="Votre nom et prénom" /></label><PhoneFields /><button className="primary-button wide-button" disabled={loading} type="submit">Enregistrer mon profil →</button></form> : <><div className="auth-tabs"><button className={mode === "login" ? "active" : ""} onClick={() => setMode("login")} type="button">Se connecter</button><button className={mode === "register" ? "active" : ""} onClick={() => setMode("register")} type="button">Créer un compte</button></div><form className="form-stack" onSubmit={submit}>{mode === "register" && <label>Nom complet<input name="name" required placeholder="Votre nom et prénom" /></label>}<PhoneFields />{mode === "register" && <p className="auth-helper">Un code à 6 chiffres vous sera demandé après l’inscription.</p>}<label>Mot de passe<input name="password" type="password" minLength={6} required placeholder="Minimum 6 caractères" /></label>{mode === "login" && <button className="forgot-password" onClick={resetPassword} type="button">Mot de passe oublié ?</button>}<button className="primary-button wide-button" disabled={loading} type="submit">{loading ? <><span className="button-spinner" />Chargement...</> : mode === "register" ? "Créer mon compte →" : "Se connecter →"}</button></form><button className="google-button" disabled={loading} onClick={googleSignIn} type="button"><span>G</span>S’inscrire avec Google</button></>}{notice && <p className="form-notice">{notice}</p>}{error && <p className="form-error">{error}</p>}{!googleUser && <p className="auth-switch">{expectedRole === "locataire" ? "Vous êtes propriétaire ? " : "Vous êtes locataire ? "}<Link href={expectedRole === "locataire" ? "/proprietaire/connexion" : "/locataire/connexion"}>Autre espace</Link></p>}</section><p className="auth-footer">Vos données sont protégées par Firebase Authentication.</p></main>;
}

function PhoneFields() { return <div className="phone-fields"><select name="country" defaultValue="+229" aria-label="Indicatif téléphonique">{countries.map((country) => <option key={country.code} value={country.code}>{country.flag} {country.name} ({country.code})</option>)}</select><input name="phone" type="tel" inputMode="numeric" placeholder="01 00 00 00" required aria-label="Numéro de téléphone" /></div>; }
