"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useState } from "react";
import { doc, getDoc, updateDoc } from "firebase/firestore";
import { auth, db } from "@/lib/firebase/client";

export function VerificationCard() { const router = useRouter(); const params = useSearchParams(); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); async function verify(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); try { const uid = params.get("uid") ?? auth.currentUser?.uid; if (!uid) throw new Error(); const snapshot = await getDoc(doc(db, "codesVerification", uid)); const data = snapshot.data(); const code = String(new FormData(event.currentTarget).get("code") ?? ""); if (!data || data.code !== code || data.expiresAt < Date.now()) throw new Error(); await updateDoc(doc(db, "users", uid), { statut: "actif" }); await updateDoc(doc(db, "codesVerification", uid), { statut: "utilise" }); const profile = await getDoc(doc(db, "users", uid)); const role = profile.data()?.role === "proprietaire" ? "proprietaire" : "locataire"; document.cookie = `bailio-status=actif; path=/; max-age=2592000; samesite=lax`; document.cookie = `bailio-role=${role}; path=/; max-age=2592000; samesite=lax`; router.push(role === "proprietaire" ? "/onboarding/proprietaire" : "/locataire/dashboard"); } catch { setError("Code incorrect ou expiré. Demandez un nouveau code."); } finally { setLoading(false); } } return <main className="auth-page"><Link className="brand auth-brand" href="/"><span className="brand-mark">B</span><span>Bail<span className="brand-accent">io</span></span></Link><section className="auth-card"><div className="auth-card-heading"><span className="auth-symbol">✓</span><p className="eyebrow">VÉRIFICATION</p><h1>Vérifiez votre compte</h1><p>Entrez le code à 6 chiffres reçu pour activer votre espace.</p></div><form className="form-stack" onSubmit={verify}><label>Code de vérification<input name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} placeholder="000000" required /></label><button className="primary-button wide-button" disabled={loading} type="submit">{loading ? "Vérification..." : "Activer mon compte →"}</button></form>{error && <p className="form-error">{error}</p>}</section></main>; }
